import { NextResponse } from "next/server";

export async function POST(req) {
  try {
    const { title, description } = await req.json();

    if (!title) {
      return NextResponse.json({ error: "Title is required" }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;

    if (apiKey) {
      // Real API Mode using Google Gemini API
      const prompt = `You are an API. Respond ONLY with a valid, parsable JSON object. No markdown, no backticks, no comments.
Schema:
{
  "subtasks": ["concise subtask 1", "concise subtask 2", ...]
}

Generate 4 to 6 concise technical subtasks (max 50 chars each) to complete task: "${title}".
${description ? `Context details: "${description}"` : ""}`;

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: prompt,
                  },
                ],
              },
            ],
            generationConfig: {
              responseMimeType: "application/json",
            },
          }),
        }
      );

      // if (!response.ok) {
      //   throw new Error(`Gemini API returned status ${response.status}`);
      // }
      if (!response.ok) {
        const errorText = await response.text();
        // console.log("🔴 GEMINI API ERROR RESPONSE BODY:", errorText);
        throw new Error(`Gemini API returned status ${response.status}: ${errorText}`);
      }

      const resData = await response.json();
      const textResponse = resData.candidates?.[0]?.content?.parts?.[0]?.text;

      // Print the exact text response generated by Gemini:
      // console.log("🟢 GEMINI API RAW TEXT RESPONSE:", textResponse);

      if (!textResponse) {
        throw new Error("Empty response from Gemini API");
      }

      let jsonText = textResponse.trim();
      
      // 1. Extract the main JSON object matching the first opening brace
      const start = jsonText.indexOf("{");
      if (start !== -1) {
        let depth = 0;
        for (let i = start; i < jsonText.length; i++) {
          if (jsonText[i] === "{") {
            depth++;
          } else if (jsonText[i] === "}") {
            depth--;
            if (depth === 0) {
              jsonText = jsonText.substring(start, i + 1);
              break;
            }
          }
        }
      }

      // 2. Clean up any trailing commas that break JSON.parse
      jsonText = jsonText.replace(/,\s*([\]}])/g, '$1');
      
      const jsonResponse = JSON.parse(jsonText);
      return NextResponse.json({ subtasks: jsonResponse.subtasks || [] });
    } else {
      // Smart Fallback Mock Mode (no API key / offline)
      const titleLower = title.toLowerCase();
      let mockSubtasks = [];

      if (
        titleLower.includes("auth") ||
        titleLower.includes("login") ||
        titleLower.includes("signup") ||
        titleLower.includes("register") ||
        titleLower.includes("user")
      ) {
        mockSubtasks = [
          "Configure Firebase Auth instance integration",
          "Design login and signup viewport templates",
          "Implement email and password validation rules",
          "Write credentials form submit handlers",
          "Setup private route guards and session listeners",
        ];
      } else if (
        titleLower.includes("layout") ||
        titleLower.includes("design") ||
        titleLower.includes("ui") ||
        titleLower.includes("component") ||
        titleLower.includes("css") ||
        titleLower.includes("style") ||
        titleLower.includes("theme")
      ) {
        mockSubtasks = [
          "Create base responsive wireframe layout blueprint",
          "Build header navigation links and logo assets",
          "Configure CSS theme styling custom tokens",
          "Inject custom fonts and typography rules",
          "Test responsive rendering on mobile viewports",
        ];
      } else if (
        titleLower.includes("database") ||
        titleLower.includes("firestore") ||
        titleLower.includes("firebase") ||
        titleLower.includes("db") ||
        titleLower.includes("api") ||
        titleLower.includes("store")
      ) {
        mockSubtasks = [
          "Establish cloud database collection security limits",
          "Initialize collections and document routing paths",
          "Write asynchronous CRUD transaction helper methods",
          "Sync data streams with global Redux state selectors",
          "Verify query indexing and response latencies",
        ];
      } else if (
        titleLower.includes("deploy") ||
        titleLower.includes("vercel") ||
        titleLower.includes("build") ||
        titleLower.includes("production")
      ) {
        mockSubtasks = [
          "Configure build pipelines and environment tokens",
          "Execute local code linting and formatter routines",
          "Run production bundle compilation checks",
          "Configure live hooks and deployment logs in cloud provider",
          "Verify domain DNS resolution and SSL security",
        ];
      } else {
        mockSubtasks = [
          "Define specific technical requirements and metrics",
          "Scaffold core directory files and import statements",
          "Implement core features and processing handlers",
          "Write error boundaries and validation checks",
          "Verify feature deliverables against PRD goals",
        ];
      }

      // Simulate network delay
      await new Promise((resolve) => setTimeout(resolve, 800));

      return NextResponse.json({ subtasks: mockSubtasks });
    }
  } catch (error) {
    console.error("AI Subtasks API error:", error);
    return NextResponse.json(
      { error: "Failed to generate subtasks: " + error.message },
      { status: 500 }
    );
  }
}
